// app/layout.js
import './styles/globals.css';  // Memastikan globals.css yang berisi font sudah diimport
import Sidebar from './components/sidebar/Sidebar'; 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="flex min-h-screen">
          <Sidebar /> 
          <main className="flex-1 bg-cyan-800 p-6">
            {children} 
          </main>
        </div>
      </body>
    </html>
  );
}
