// app/layout.js
import '@/app/styles/globals.css';  // Memastikan globals.css yang berisi font sudah diimport
import Sidebar from '@/app/components/sidebar/Sidebar'; 

export const metadata = {
  title: "Manajemen Gudang Hartindo Surya Medika",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
      // <body className="antialiased">
        <div className="flex min-h-screen">
          <Sidebar /> 
          <main className=" ml-64 flex-1 bg-slate-100 p-6">
            {children} 
          </main>
        </div>
      // </body>
    // </html>
  );
}
